### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by frinux**
Avoid error and stacktrace when installing requirement from ansible-galaxy command

### CODE REVIEW

**Comment by kosssi** [comment]
Thanks !!!

**Comment by kosssi** [comment]
If you can vote for this role in ansible galaxy is the best ;)

**Comment by kosssi** [comment]
@frinux v1.1.1 is for you ;)

**Comment by frinux** [comment]
Wow that was quick, thanks!

I just submitted a rating on Galaxy

Good work, see you

François LE QUEMENER

2015-08-28 10:39 GMT+02:00 Simon notifications@github.com:

**Pull request merged**
